"""empty message

Revision ID: 7017d9095963
Revises: 9d3a183554be
Create Date: 2017-03-14 10:01:12.334924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7017d9095963'
down_revision = '9d3a183554be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incoming_log', sa.Column('generalized_data_incoming', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incoming_log', 'generalized_data_incoming')
    # ### end Alembic commands ###
